# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.20'
        cache: true
        cache-dependency-path: go.sum
    - run: go version

    - name: Build
      run: go build -v ./...

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1

    # - name: Install gcov2lcov
    #   run: |
    #     go install github.com/jandelgado/gcov2lcov@latest
    # - name: Test and Generate coverage report
    #   run: |
    #     go test -coverprofile=coverage.out && \
    #     gcov2lcov -infile=coverage.out -outfile=coverage.lcov
    # - name: CodeClimate
    #   uses: paambaati/codeclimate-action@v6.0.0
    #   env:
    #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    #   with:
    #     debug: true
    #     coverageLocations: ${{github.workspace}}/coverage.lcov:lcov
